library(dplyr)
library(readxl)
library(tidyr)
titanic_data <- read_xls("titanic3.xls")
titanic_tbl <- tbl_df(titanic_data)
titanic_tbl$embarked <- replace_na(titanic_tbl$embarked, "S")
mean_age <- mean(titanic_tbl$age, na.rm = TRUE)
titanic_tbl$age <- replace_na(titanic_tbl$age, mean_age)
titanic_tbl$boat <- replace_na(titanic_tbl$boat, "None")
titanic_tbl <- titanic_tbl %>% mutate(has_cabin_number = ifelse(is.na(titanic_tbl$cabin),0, 1))
write.csv(titanic_tbl, "titanic_clean.csv")